
-- 6. Districts table
CREATE TABLE districts (
    district_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    district_name TEXT,
    logo TEXT,
    province TEXT,
    office_address TEXT,
    contact TEXT,
    email TEXT
);

ALTER TABLE districts ENABLE ROW LEVEL SECURITY;

-- Policy: allow all reads
CREATE POLICY "districts_select_all"
ON districts
FOR SELECT
USING (true);

-- 7. Municipalities table
CREATE TABLE municipalities (
    municipality_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    municipal_name TEXT,
    logo TEXT,
    district_id BIGINT REFERENCES districts(district_id)
);

ALTER TABLE municipalities ENABLE ROW LEVEL SECURITY;

-- Policy: allow all reads
CREATE POLICY "municipalities_select_all"
ON municipalities
FOR SELECT
USING (true);
